/**
 * Do not edit directly, this file was auto-generated.
 */

export default {
  stabilo: {
    point88: {
      11: {
        $value: "#a4daf3",
        $description: "ice blue",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#a4daf3",
          $description: "ice blue",
          $type: "color",
        },
        name: "11",
        attributes: {},
        path: ["stabilo", "point88", "11"],
      },
      12: {
        $value: "#8ec3b8",
        $description: "eucalyptus",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#8ec3b8",
          $description: "eucalyptus",
          $type: "color",
        },
        name: "12",
        attributes: {},
        path: ["stabilo", "point88", "12"],
      },
      13: {
        $value: "#37b6aa",
        $description: "ice green",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#37b6aa",
          $description: "ice green",
          $type: "color",
        },
        name: "13",
        attributes: {},
        path: ["stabilo", "point88", "13"],
      },
      14: {
        $value: "#c9d76e",
        $description: "lime green",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#c9d76e",
          $description: "lime green",
          $type: "color",
        },
        name: "14",
        attributes: {},
        path: ["stabilo", "point88", "14"],
      },
      16: {
        $value: "#87c695",
        $description: "mint green",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#87c695",
          $description: "mint green",
          $type: "color",
        },
        name: "16",
        attributes: {},
        path: ["stabilo", "point88", "16"],
      },
      17: {
        $value: "#E496C0",
        $description: "heliotrope",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#E496C0",
          $description: "heliotrope",
          $type: "color",
        },
        name: "17",
        attributes: {},
        path: ["stabilo", "point88", "17"],
      },
      19: {
        $value: "#b32451",
        $description: "purple",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#b32451",
          $description: "purple",
          $type: "color",
        },
        name: "19",
        attributes: {},
        path: ["stabilo", "point88", "19"],
      },
      22: {
        $value: "#22165c",
        $description: "nightblue",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#22165c",
          $description: "nightblue",
          $type: "color",
        },
        name: "22",
        attributes: {},
        path: ["stabilo", "point88", "22"],
      },
      23: {
        $value: "#f7eaa0",
        $description: "light yellow",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#f7eaa0",
          $description: "light yellow",
          $type: "color",
        },
        name: "23",
        attributes: {},
        path: ["stabilo", "point88", "23"],
      },
      24: {
        $value: "#f6ea4c",
        $description: "lemon yellow",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#f6ea4c",
          $description: "lemon yellow",
          $type: "color",
        },
        name: "24",
        attributes: {},
        path: ["stabilo", "point88", "24"],
      },
      25: {
        $value: "#e3b582",
        $description: "light orange",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#e3b582",
          $description: "light orange",
          $type: "color",
        },
        name: "25",
        attributes: {},
        path: ["stabilo", "point88", "25"],
      },
      26: {
        $value: "#f6af94",
        $description: "apricot",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#f6af94",
          $description: "apricot",
          $type: "color",
        },
        name: "26",
        attributes: {},
        path: ["stabilo", "point88", "26"],
      },
      28: {
        $value: "#e5b5b2",
        $description: "blush",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#e5b5b2",
          $description: "blush",
          $type: "color",
        },
        name: "28",
        attributes: {},
        path: ["stabilo", "point88", "28"],
      },
      29: {
        $value: "#f08a9f",
        $description: "light pink",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#f08a9f",
          $description: "light pink",
          $type: "color",
        },
        name: "29",
        attributes: {},
        path: ["stabilo", "point88", "29"],
      },
      30: {
        $value: "#ec6724",
        $description: "pale vermillion",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#ec6724",
          $description: "pale vermillion",
          $type: "color",
        },
        name: "30",
        attributes: {},
        path: ["stabilo", "point88", "30"],
      },
      31: {
        $value: "#008ed0",
        $description: "light blue",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#008ed0",
          $description: "light blue",
          $type: "color",
        },
        name: "31",
        attributes: {},
        path: ["stabilo", "point88", "31"],
      },
      32: {
        $value: "#0085cd",
        $description: "blue",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#0085cd",
          $description: "blue",
          $type: "color",
        },
        name: "32",
        attributes: {},
        path: ["stabilo", "point88", "32"],
      },
      33: {
        $value: "#a2bf16",
        $description: "apple green",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#a2bf16",
          $description: "apple green",
          $type: "color",
        },
        name: "33",
        attributes: {},
        path: ["stabilo", "point88", "33"],
      },
      34: {
        $value: "#a3bf73",
        $description: "pistachio",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#a3bf73",
          $description: "pistachio",
          $type: "color",
        },
        name: "34",
        attributes: {},
        path: ["stabilo", "point88", "34"],
      },
      35: {
        $value: "#7f8c47",
        $description: "moss green",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#7f8c47",
          $description: "moss green",
          $type: "color",
        },
        name: "35",
        attributes: {},
        path: ["stabilo", "point88", "35"],
      },
      36: {
        $value: "#00924e",
        $description: "green",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#00924e",
          $description: "green",
          $type: "color",
        },
        name: "36",
        attributes: {},
        path: ["stabilo", "point88", "36"],
      },
      37: {
        $value: "#96864c",
        $description: "mud green",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#96864c",
          $description: "mud green",
          $type: "color",
        },
        name: "37",
        attributes: {},
        path: ["stabilo", "point88", "37"],
      },
      38: {
        $value: "#c33f34",
        $description: "sanguine",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#c33f34",
          $description: "sanguine",
          $type: "color",
        },
        name: "38",
        attributes: {},
        path: ["stabilo", "point88", "38"],
      },
      40: {
        $value: "#e3000f",
        $description: "red",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#e3000f",
          $description: "red",
          $type: "color",
        },
        name: "40",
        attributes: {},
        path: ["stabilo", "point88", "40"],
      },
      41: {
        $value: "#0f4295",
        $description: "blue",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#0f4295",
          $description: "blue",
          $type: "color",
        },
        name: "41",
        attributes: {},
        path: ["stabilo", "point88", "41"],
      },
      43: {
        $value: "#75b842",
        $description: "light green",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#75b842",
          $description: "light green",
          $type: "color",
        },
        name: "43",
        attributes: {},
        path: ["stabilo", "point88", "43"],
      },
      44: {
        $value: "#fad200",
        $description: "yellow",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#fad200",
          $description: "yellow",
          $type: "color",
        },
        name: "44",
        attributes: {},
        path: ["stabilo", "point88", "44"],
      },
      45: {
        $value: "#6d402c",
        $description: "brown",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#6d402c",
          $description: "brown",
          $type: "color",
        },
        name: "45",
        attributes: {},
        path: ["stabilo", "point88", "45"],
      },
      46: {
        $value: "#00131a",
        $description: "black",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#00131a",
          $description: "black",
          $type: "color",
        },
        name: "46",
        attributes: {},
        path: ["stabilo", "point88", "46"],
      },
      47: {
        $value: "#ca4d53",
        $description: "rust red",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#ca4d53",
          $description: "rust red",
          $type: "color",
        },
        name: "47",
        attributes: {},
        path: ["stabilo", "point88", "47"],
      },
      48: {
        $value: "#e3000f",
        $description: "carmine",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#e3000f",
          $description: "carmine",
          $type: "color",
        },
        name: "48",
        attributes: {},
        path: ["stabilo", "point88", "48"],
      },
      49: {
        $value: "#ec616b",
        $description: "strawberry red",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#ec616b",
          $description: "strawberry red",
          $type: "color",
        },
        name: "49",
        attributes: {},
        path: ["stabilo", "point88", "49"],
      },
      50: {
        $value: "#ce1041",
        $description: "dark red",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#ce1041",
          $description: "dark red",
          $type: "color",
        },
        name: "50",
        attributes: {},
        path: ["stabilo", "point88", "50"],
      },
      51: {
        $value: "#009bb4",
        $description: "turquoise blue",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#009bb4",
          $description: "turquoise blue",
          $type: "color",
        },
        name: "51",
        attributes: {},
        path: ["stabilo", "point88", "51"],
      },
      53: {
        $value: "#007667",
        $description: "pine green",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#007667",
          $description: "pine green",
          $type: "color",
        },
        name: "53",
        attributes: {},
        path: ["stabilo", "point88", "53"],
      },
      54: {
        $value: "#ea5725",
        $description: "orange",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#ea5725",
          $description: "orange",
          $type: "color",
        },
        name: "54",
        attributes: {},
        path: ["stabilo", "point88", "54"],
      },
      55: {
        $value: "#5b2282",
        $description: "violet",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#5b2282",
          $description: "violet",
          $type: "color",
        },
        name: "55",
        attributes: {},
        path: ["stabilo", "point88", "55"],
      },
      56: {
        $value: "#ed6ea7",
        $description: "pink",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#ed6ea7",
          $description: "pink",
          $type: "color",
        },
        name: "56",
        attributes: {},
        path: ["stabilo", "point88", "56"],
      },
      57: {
        $value: "#1cbade",
        $description: "azure",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#1cbade",
          $description: "azure",
          $type: "color",
        },
        name: "57",
        attributes: {},
        path: ["stabilo", "point88", "57"],
      },
      58: {
        $value: "#9a35b5",
        $description: "lilac",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#9a35b5",
          $description: "lilac",
          $type: "color",
        },
        name: "58",
        attributes: {},
        path: ["stabilo", "point88", "58"],
      },
      59: {
        $value: "#bc99cb",
        $description: "light lilac",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#bc99cb",
          $description: "light lilac",
          $type: "color",
        },
        name: "59",
        attributes: {},
        path: ["stabilo", "point88", "59"],
      },
      60: {
        $value: "#955595",
        $description: "plum",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#955595",
          $description: "plum",
          $type: "color",
        },
        name: "60",
        attributes: {},
        path: ["stabilo", "point88", "60"],
      },
      62: {
        $value: "#916792",
        $description: "grey violet",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#916792",
          $description: "grey violet",
          $type: "color",
        },
        name: "62",
        attributes: {},
        path: ["stabilo", "point88", "62"],
      },
      63: {
        $value: "#415e38",
        $description: "olive green",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#415e38",
          $description: "olive green",
          $type: "color",
        },
        name: "63",
        attributes: {},
        path: ["stabilo", "point88", "63"],
      },
      65: {
        $value: "#685341",
        $description: "umber",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#685341",
          $description: "umber",
          $type: "color",
        },
        name: "65",
        attributes: {},
        path: ["stabilo", "point88", "65"],
      },
      66: {
        $value: "#bcae63",
        $description: "khaki",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#bcae63",
          $description: "khaki",
          $type: "color",
        },
        name: "66",
        attributes: {},
        path: ["stabilo", "point88", "66"],
      },
      67: {
        $value: "#d4d072",
        $description: "mustard",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#d4d072",
          $description: "mustard",
          $type: "color",
        },
        name: "67",
        attributes: {},
        path: ["stabilo", "point88", "67"],
      },
      75: {
        $value: "#834E38",
        $description: "sienna",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#834E38",
          $description: "sienna",
          $type: "color",
        },
        name: "75",
        attributes: {},
        path: ["stabilo", "point88", "75"],
      },
      85: {
        $value: "#e5c17e",
        $description: "papaya",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#e5c17e",
          $description: "papaya",
          $type: "color",
        },
        name: "85",
        attributes: {},
        path: ["stabilo", "point88", "85"],
      },
      86: {
        $value: "#e7d5b8",
        $description: "beige",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#e7d5b8",
          $description: "beige",
          $type: "color",
        },
        name: "86",
        attributes: {},
        path: ["stabilo", "point88", "86"],
      },
      87: {
        $value: "#d6b63b",
        $description: "curry",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#d6b63b",
          $description: "curry",
          $type: "color",
        },
        name: "87",
        attributes: {},
        path: ["stabilo", "point88", "87"],
      },
      88: {
        $value: "#d19a56",
        $description: "light ochre",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#d19a56",
          $description: "light ochre",
          $type: "color",
        },
        name: "88",
        attributes: {},
        path: ["stabilo", "point88", "88"],
      },
      89: {
        $value: "#c3611a",
        $description: "dark ochre",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#c3611a",
          $description: "dark ochre",
          $type: "color",
        },
        name: "89",
        attributes: {},
        path: ["stabilo", "point88", "89"],
      },
      93: {
        $value: "#b0aca4",
        $description: "warm grey",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#b0aca4",
          $description: "warm grey",
          $type: "color",
        },
        name: "93",
        attributes: {},
        path: ["stabilo", "point88", "93"],
      },
      94: {
        $value: "#bac9d8",
        $description: "light grey",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#bac9d8",
          $description: "light grey",
          $type: "color",
        },
        name: "94",
        attributes: {},
        path: ["stabilo", "point88", "94"],
      },
      95: {
        $value: "#949ca7",
        $description: "medium cold grey",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#949ca7",
          $description: "medium cold grey",
          $type: "color",
        },
        name: "95",
        attributes: {},
        path: ["stabilo", "point88", "95"],
      },
      96: {
        $value: "#6a7587",
        $description: "dark grey",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#6a7587",
          $description: "dark grey",
          $type: "color",
        },
        name: "96",
        attributes: {},
        path: ["stabilo", "point88", "96"],
      },
      97: {
        $value: "#4e525c",
        $description: "deep cold grey",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#4e525c",
          $description: "deep cold grey",
          $type: "color",
        },
        name: "97",
        attributes: {},
        path: ["stabilo", "point88", "97"],
      },
      98: {
        $value: "#1b426e",
        $description: "Payne's grey",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#1b426e",
          $description: "Payne's grey",
          $type: "color",
        },
        name: "98",
        attributes: {},
        path: ["stabilo", "point88", "98"],
      },
      "024": {
        $value: "#fce900",
        $description: "neon yellow",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#fce900",
          $description: "neon yellow",
          $type: "color",
        },
        name: "024",
        attributes: {},
        path: ["stabilo", "point88", "024"],
      },
      "031": {
        $value: "#3fc0f0",
        $description: "neon blue",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#3fc0f0",
          $description: "neon blue",
          $type: "color",
        },
        name: "031",
        attributes: {},
        path: ["stabilo", "point88", "031"],
      },
      "033": {
        $value: "#85bd3f",
        $description: "neon green",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#85bd3f",
          $description: "neon green",
          $type: "color",
        },
        name: "033",
        attributes: {},
        path: ["stabilo", "point88", "033"],
      },
      "040": {
        $value: "#f4a7b6",
        $description: "neon red",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#f4a7b6",
          $description: "neon red",
          $type: "color",
        },
        name: "040",
        attributes: {},
        path: ["stabilo", "point88", "040"],
      },
      "054": {
        $value: "#fbbb32",
        $description: "neon orange",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#fbbb32",
          $description: "neon orange",
          $type: "color",
        },
        name: "054",
        attributes: {},
        path: ["stabilo", "point88", "054"],
      },
      "056": {
        $value: "#ed6da6",
        $description: "neon pink",
        filePath: "src/stabilo.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#ed6da6",
          $description: "neon pink",
          $type: "color",
        },
        name: "056",
        attributes: {},
        path: ["stabilo", "point88", "056"],
      },
    },
  },
  staedler: {
    triplusFineliner334: {
      1: {
        $value: "#FAEE03",
        $description: "yellow",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#FAEE03",
          $description: "yellow",
          $type: "color",
        },
        name: "1",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "1"],
      },
      2: {
        $value: "#D81300",
        $description: "red",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#D81300",
          $description: "red",
          $type: "color",
        },
        name: "2",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "2"],
      },
      3: {
        $value: "#223C9F",
        $description: "blue",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#223C9F",
          $description: "blue",
          $type: "color",
        },
        name: "3",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "3"],
      },
      4: {
        $value: "#F86F02",
        $description: "orange",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#F86F02",
          $description: "orange",
          $type: "color",
        },
        name: "4",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "4"],
      },
      5: {
        $value: "#0F7730",
        $description: "green",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#0F7730",
          $description: "green",
          $type: "color",
        },
        name: "5",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "5"],
      },
      6: {
        $value: "#58007A",
        $description: "violet",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#58007A",
          $description: "violet",
          $type: "color",
        },
        name: "6",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "6"],
      },
      7: {
        $value: "#D36602",
        $description: "light brown",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#D36602",
          $description: "light brown",
          $type: "color",
        },
        name: "7",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "7"],
      },
      8: {
        $value: "#5E575F",
        $description: "grey",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#5E575F",
          $description: "grey",
          $type: "color",
        },
        name: "8",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "8"],
      },
      9: {
        $value: "#000000",
        $description: "black",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#000000",
          $description: "black",
          $type: "color",
        },
        name: "9",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "9"],
      },
      20: {
        $value: "#F90E92",
        $description: "magenta",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#F90E92",
          $description: "magenta",
          $type: "color",
        },
        name: "20",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "20"],
      },
      21: {
        $value: "#FCBDD5",
        $description: "light rosé",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#FCBDD5",
          $description: "light rosé",
          $type: "color",
        },
        name: "21",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "21"],
      },
      23: {
        $value: "#B20F52",
        $description: "bordeaux",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#B20F52",
          $description: "bordeaux",
          $type: "color",
        },
        name: "23",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "23"],
      },
      29: {
        $value: "#982533",
        $description: "carmine red",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#982533",
          $description: "carmine red",
          $type: "color",
        },
        name: "29",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "29"],
      },
      30: {
        $value: "#669BD1",
        $description: "pale blue",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#669BD1",
          $description: "pale blue",
          $type: "color",
        },
        name: "30",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "30"],
      },
      34: {
        $value: "#89CAE8",
        $description: "aqua blue",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#89CAE8",
          $description: "aqua blue",
          $type: "color",
        },
        name: "34",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "34"],
      },
      36: {
        $value: "#2D4061",
        $description: "indigo blue",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#2D4061",
          $description: "indigo blue",
          $type: "color",
        },
        name: "36",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "36"],
      },
      37: {
        $value: "#3393CF",
        $description: "ultramarine blue",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#3393CF",
          $description: "ultramarine blue",
          $type: "color",
        },
        name: "37",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "37"],
      },
      43: {
        $value: "#FBCC8D",
        $description: "light orange",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#FBCC8D",
          $description: "light orange",
          $type: "color",
        },
        name: "43",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "43"],
      },
      48: {
        $value: "#B15026",
        $description: "kalahari orange",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#B15026",
          $description: "kalahari orange",
          $type: "color",
        },
        name: "48",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "48"],
      },
      51: {
        $value: "#D5EC7A",
        $description: "willow green",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#D5EC7A",
          $description: "willow green",
          $type: "color",
        },
        name: "51",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "51"],
      },
      53: {
        $value: "#CBDD71",
        $description: "lime green",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#CBDD71",
          $description: "lime green",
          $type: "color",
        },
        name: "53",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "53"],
      },
      54: {
        $value: "#7BBCB8",
        $description: "turquoise",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#7BBCB8",
          $description: "turquoise",
          $type: "color",
        },
        name: "54",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "54"],
      },
      55: {
        $value: "#053F1E",
        $description: "green earth",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#053F1E",
          $description: "green earth",
          $type: "color",
        },
        name: "55",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "55"],
      },
      57: {
        $value: "#4D4C14",
        $description: "olive green",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#4D4C14",
          $description: "olive green",
          $type: "color",
        },
        name: "57",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "57"],
      },
      61: {
        $value: "#A00088",
        $description: "red violet",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#A00088",
          $description: "red violet",
          $type: "color",
        },
        name: "61",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "61"],
      },
      62: {
        $value: "#BE89D1",
        $description: "lavender",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#BE89D1",
          $description: "lavender",
          $type: "color",
        },
        name: "62",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "62"],
      },
      63: {
        $value: "#709FCB",
        $description: "delft blue",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#709FCB",
          $description: "delft blue",
          $type: "color",
        },
        name: "63",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "63"],
      },
      69: {
        $value: "#3F215F",
        $description: "dark mauve",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#3F215F",
          $description: "dark mauve",
          $type: "color",
        },
        name: "69",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "69"],
      },
      73: {
        $value: "#BA4109",
        $description: "burnt sienna",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#BA4109",
          $description: "burnt sienna",
          $type: "color",
        },
        name: "73",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "73"],
      },
      76: {
        $value: "#641400",
        $description: "Brown",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#641400",
          $description: "Brown",
          $type: "color",
        },
        name: "76",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "76"],
      },
      77: {
        $value: "#5F4E46",
        $description: "tobacco brown",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#5F4E46",
          $description: "tobacco brown",
          $type: "color",
        },
        name: "77",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "77"],
      },
      82: {
        $value: "#AFB2B9",
        $description: "light grey",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#AFB2B9",
          $description: "light grey",
          $type: "color",
        },
        name: "82",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "82"],
      },
      101: {
        $value: "#FAEE03",
        $description: "neon yellow",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#FAEE03",
          $description: "neon yellow",
          $type: "color",
        },
        name: "101",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "101"],
      },
      110: {
        $value: "#F9C300",
        $description: "bright yellow",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#F9C300",
          $description: "bright yellow",
          $type: "color",
        },
        name: "110",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "110"],
      },
      201: {
        $value: "#BC171D",
        $description: "neon red",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#BC171D",
          $description: "neon red",
          $type: "color",
        },
        name: "201",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "201"],
      },
      221: {
        $value: "#FB5BBA",
        $description: "neon pink",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#FB5BBA",
          $description: "neon pink",
          $type: "color",
        },
        name: "221",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "221"],
      },
      222: {
        $value: "#FAB296",
        $description: "salmon",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#FAB296",
          $description: "salmon",
          $type: "color",
        },
        name: "222",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "222"],
      },
      260: {
        $value: "#96698A",
        $description: "mauve",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#96698A",
          $description: "mauve",
          $type: "color",
        },
        name: "260",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "260"],
      },
      301: {
        $value: "#40BBFB",
        $description: "neon blue",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#40BBFB",
          $description: "neon blue",
          $type: "color",
        },
        name: "301",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "301"],
      },
      401: {
        $value: "#E8BC35",
        $description: "neon orange",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#E8BC35",
          $description: "neon orange",
          $type: "color",
        },
        name: "401",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "401"],
      },
      501: {
        $value: "#3EA83C",
        $description: "neon green",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#3EA83C",
          $description: "neon green",
          $type: "color",
        },
        name: "501",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "501"],
      },
      550: {
        $value: "#37C37A",
        $description: "pale green",
        filePath: "src/staedler.json",
        isSource: true,
        $type: "color",
        original: {
          $value: "#37C37A",
          $description: "pale green",
          $type: "color",
        },
        name: "550",
        attributes: {},
        path: ["staedler", "triplusFineliner334", "550"],
      },
    },
  },
};
